defaults:
  - _self_
  - pipeline: ???
  - aligner: none
  - experiment: null

hydra:
  job:
    chdir: True

log_to_wandb: true
wandb_project: nlp_ilp
problem: annotation_projection

tgt_lang: ???
src_lang: en

cached_step_paths: null

disable_hf_caching: true