defaults:
  - _self_
  - pipeline: ???
  - aligner: simalign_mbert_iterative
  - experiment: null

hydra:
  job:
    chdir: True

log_to_wandb: true
wandb_project: nlp_ilp

tgt_lang: ???

cached_step_paths: null

disable_hf_caching: true