load_ds:
  deps: []
  transform:
    _target_: src.pipeline.data.LoadDataset
    dataset_path: ???
    cfg_name: null
    split: null
    streaming: false
    local: false
load_entities:
  deps: []
  transform:
    _target_: src.pipeline.data.LoadDataset
    dataset_path: ???
    cfg_name: null
    split: null
    streaming: false
    local: true
merge_datasets:
  deps: [load_entities, load_ds]
  transform:
    _target_: src.pipeline.data.ConcatDatasets
cand_extraction:
  deps: [merge_datasets]
  transform:
    _target_: src.pipeline.cand_extractor.ContiniousSubrangeExtractor
    tgt_words_column: tokens
    out_column: tgt_candidates
    min_words: 1
    max_words: 7
project:
  deps: [cand_extraction]
  transform:
    _target_: src.pipeline.projection.RangeILPProjection
    tgt_words_column: tokens
    src_words_column: src_words
    src_entities_column: src_entities
    tgt_cand_column: ${pipeline.cand_extraction.transform.out_column}
    out_column: labels
    n_projected: 1
    proj_constraint: LESS_OR_EQUAL
    solver: GUROBI
    num_proc: null
    cost_params:
      - type: nmtscore
        tgt_lang: ???
        nmt_model: nllb-200-distilled-600M
        device: 0
        batch_size: ???
        src_lang: eng_Latn
        score_method: direct
        normalize: True
        both_directions: True
        threshold: 0.1
        use_cache: True
intrinsic_eval:
  deps: [project]
  transform:
    _target_: src.pipeline.eval.SeqEvalIntrinsicEvaluation
    orig_column: ner_tags
    gen_column: ${pipeline.project.transform.out_column}
    gen_as_tags: False
    log_to_wandb: ${log_to_wandb}
    batch_size: 1000
cost_eval:
  deps: [project]
  transform:
    _target_: src.pipeline.eval.ILPObjectiveEvaluation
    log_to_wandb: ${log_to_wandb}